name: Backend server actions

on:
  push:
    branches:
    - '*'

jobs:
  build:
    name: Build docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  lint:
    name: Check code lint with checkstyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dbelyaev/action-checkstyle@master
      with:
        reporter: github-pr-check
        level: error
        fail_on_error: true